###By Neftali Ramirez Chavez
name: cd.invex-ecosystem
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "plusnetwork-api-employee" #Must be unique in Heroku
          heroku_email: "nefkon8002@gmail.com"
